name: Docker build and push

on:
  push:
    tags: 
      - 'v*.*.*'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Download npm dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.x
          cache: "npm"
      - run: npm i

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pokemon-nodejs:${{ env.RELEASE_VERSION }}
